const express = require('express')
const app = express()
const kelasRouter = require('./KelasRouter')
const siswaRouter = require('./SiswaRouter')
const authRouter = require('./AuthRouter')
const absenRouter = require('./AbsenRouter')
const guruRouter = require('./GuruRouter')
const hariRouter = require('./HariRouter')
const jampelRouter = require('./JamPelajaranRouter')
const liburRouter = require('./LiburRouter')
const userRouter = require('./UserRouter')
const pembayaranRouter = require('./PembayaranRouter')
const transaksiRouter = require('./TransaksiRouter')
const jadwalRouter = require('./JadwalRouter')

app.use(siswaRouter)
app.use(kelasRouter)
app.use(absenRouter)
app.use(guruRouter)
app.use(hariRouter)
app.use(jampelRouter)
app.use(liburRouter)
app.use(userRouter)
app.use(pembayaranRouter)
app.use(transaksiRouter)
app.use(jadwalRouter)
app.use(authRouter)

module.exports = app