const express = require('express')
const app = express()
const kelasRouter = require('./KelasRouter')
const siswaRouter = require('./SiswaRouter')
const authRouter = require('./AuthRouter')
const absenRouter = require('./AbsenRouter')
const guruRouter = require('./GuruRouter')
const hariRouter = require('./HariRouter')
const jampelRouter = require('./JamPelajaranRouter')
const liburRouter = require('./LiburRouter')
const userRouter = require('./UserRouter')
const pembayaranRouter = require('./PembayaranRouter')
const transaksiRouter = require('./TransaksiRouter')
const jadwalRouter = require('./JadwalRouter')
const navbarRouter = require('./NavbarRouter')
const accessRouter = require('./AccessRouter')
const biodataRouter = require('./BiodataRouter')
const jurnalRouter = require('./JurnalRouter')
const roleRouter = require('./RoleRouter')
const sectionRouter = require('./SectionRouter')
const menuRouter = require('./MenuRouter')
const submenuRouter = require('./SubmenuRouter')
const whatsappRouter = require('./WhatsAppRouter')

app.use(navbarRouter)
app.use(accessRouter)
app.use(siswaRouter)
app.use(kelasRouter)
app.use(absenRouter)
app.use(guruRouter)
app.use(hariRouter)
app.use(jampelRouter)
app.use(liburRouter)
app.use(userRouter)
app.use(pembayaranRouter)
app.use(transaksiRouter)
app.use(jadwalRouter)
app.use(biodataRouter)
app.use(jurnalRouter)
app.use(whatsappRouter)
app.use(roleRouter)
app.use(sectionRouter)
app.use(menuRouter)
app.use(submenuRouter)
app.use(authRouter)

module.exports = app